modLoader="javafml"
loaderVersion="[31,)"
#issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId="divide"
version="${file.jarVersion}"
displayName="Divide"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
#logoFile="examplemod.png"
#credits="Me hehe"
#authors="possible_triangle"
description='''
Dividing the playerbase is now a feature
'''

[[dependencies.divide]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.divide]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
