services:
   client:
      image: dockergelb/divide-client
      container_name: divide_client
      expose: [80]

   server:
      image: dockergelb/divide-server
      container_name: divide_server
      expose: [8080]
      environment:
         MONGO_URI: mongodb://database:27017
         MONGO_DB: db

   database:
      image: mongo:4
      container_name: divide_db
      expose: [27017]
      volumes:
         - db:/data/db
