name: Build Frontend

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [web/client/**]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build & Publish Container
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: ${{ secrets.DOCKER_USERNAME }}/divide-client
          context: web/client
