name: Test Frontend

on:
  workflow_dispatch:
  push:
    branches-ignore: [main]
    paths: [web/client/**]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install dependencies
        run: yarn install --pure-lock
        working-directory: web/client

      - run: yarn test-all
        working-directory: web/client
